In [1]:
import numpy as np
from generate_random_board import generate_sudoku, is_valid
from solve_puzzle import solve_with_cp

In [17]:
board = generate_sudoku()
board

array([[4, 8, 1, 6, 9, 5, 7, 3, 2],
       [2, 7, 3, 4, 1, 8, 9, 6, 5],
       [9, 5, 6, 2, 7, 3, 8, 1, 4],
       [1, 2, 8, 7, 4, 6, 5, 9, 3],
       [7, 9, 4, 5, 3, 2, 6, 8, 1],
       [6, 3, 5, 9, 8, 1, 2, 4, 7],
       [8, 1, 7, 3, 5, 9, 4, 2, 6],
       [3, 4, 2, 8, 6, 7, 1, 5, 9],
       [5, 6, 9, 1, 2, 4, 3, 7, 8]])

## Randomly remove 15 elements

In [18]:
import random

In [19]:
iterated = set()
num_removed = 0
while num_removed < 15:
    i = random.randint(0,8)
    j =  random.randint(0,8)
    if (i,j) not in iterated:
        board[i,j] = 0
        num_removed += 1

In [13]:
board = np.array(
    [[5, 4, 9, 0, 0, 1, 7, 3, 8],
     [3, 6, 7, 0, 0, 8, 0, 0, 1],
     [2, 0, 0, 0, 7, 3, 0, 4, 0],
     [0, 0, 0, 9, 0, 0, 0, 0, 5],
     [0, 0, 0, 7, 0, 5, 4, 6, 0],
     [1, 3, 5, 8, 4, 0, 0, 7, 0],
     [0, 0, 4, 0, 0, 0, 3, 0, 7],
     [7, 8, 0, 3, 5, 0, 0, 0, 6],
     [0, 2, 3, 0, 8, 0, 0, 0, 0]],
    dtype=np.uint8
)

In [14]:
board

array([[5, 4, 9, 0, 0, 1, 7, 3, 8],
       [3, 6, 7, 0, 0, 8, 0, 0, 1],
       [2, 0, 0, 0, 7, 3, 0, 4, 0],
       [0, 0, 0, 9, 0, 0, 0, 0, 5],
       [0, 0, 0, 7, 0, 5, 4, 6, 0],
       [1, 3, 5, 8, 4, 0, 0, 7, 0],
       [0, 0, 4, 0, 0, 0, 3, 0, 7],
       [7, 8, 0, 3, 5, 0, 0, 0, 6],
       [0, 2, 3, 0, 8, 0, 0, 0, 0]], dtype=uint8)

In [20]:
solved_puzzle, _  = solve_with_cp(board)

In [21]:
solved_puzzle

array([[4, 8, 1, 6, 9, 5, 7, 3, 2],
       [2, 7, 3, 4, 1, 8, 9, 6, 5],
       [9, 5, 6, 2, 7, 3, 8, 1, 4],
       [1, 2, 8, 7, 4, 6, 5, 9, 3],
       [7, 9, 4, 5, 3, 2, 6, 8, 1],
       [6, 3, 5, 9, 8, 1, 2, 4, 7],
       [8, 1, 7, 3, 5, 9, 4, 2, 6],
       [3, 4, 2, 8, 6, 7, 1, 5, 9],
       [5, 6, 9, 1, 2, 4, 3, 7, 8]], dtype=uint8)